### ISSUE TITLE
Will throw an exception if resolving using Coursier

### ISSUE THREAD

**Issue by coltfred** [frugalmechanic/fm-sbt-s3-resolver#27]
If you use the [coursier](https://github.com/coursier/coursier) plugin for resolution (instead of the ivy one), the code [here](https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/master/src/main/scala/fm/sbt/s3/Handler.scala#L24) will be called and it will throw.

```
coursier.ResolutionException: Exception during resolution
Caused by: scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
        at fm.sbt.s3.Handler.openConnection(Handler.scala:24)
        at java.net.URL.openConnection(URL.java:979)
        at coursier.Cache$.coursier$Cache$$urlConn$1(Cache.scala:347)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$24$$anonfun$apply$25.apply(Cache.scala:561)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$24$$anonfun$apply$25.apply(Cache.scala:553)
        at coursier.Cache$.coursier$Cache$$downloading(Cache.scala:206)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$24.apply(Cache.scala:553)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$24.apply(Cache.scala:553)
```

To reproduce I added:
`addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")` as a plugin and attempted to build a project which has a package hosted on s3.

**Comment by tpunder** [comment]
@coltfred Thanks for reporting.  I was actually also trying to play around with coursier a few days ago and ran into the same issue so there is a high likelihood that I'll look into this soon and see what it takes to make this compatible with coursier.

**Comment by coltfred** [comment]
@tpunder Thanks! I was attempting to use [Sbtix](https://github.com/teozkr/Sbtix) and it requires coursier to work, so I'm kind of at an impasse. I appreciate you taking a look.

**Comment by tpunder** [comment]
@coltfred I've taken an initial stab at implementing support for Coursier in https://github.com/frugalmechanic/fm-sbt-s3-resolver/commit/1aa10983e3ba70eefef014fbdd57fb6a66c0a47f and have published it as 0.10.0-SNAPSHOT to Sonatype.  Can you try it out and see if it works for you?

**Comment by coltfred** [comment]
Seems to work! Thanks a bunch! I'll poke at it more tonight, but just firing up coursier and fetching the artifacts from S3 seemed to work great!

**Comment by tpunder** [comment]
FYI I've published version 0.10.0 to Maven Central.  I'll close this issue but feel free to re-open (or open a new one) if you run into any more issues.

**Comment by coltfred** [comment]
Will do! Thank you!

**Comment by l15k4** [comment]
Btw I noticed that a combination of `coursier` and `fm-sbt-s3-resolver` leads to strange dependency updates - downloads of poms of all artifacts which takes some time. I dunno why that is, probably some project settings combination of these two plugins.
