### ISSUE TITLE
Resolving plugins with s3

### ISSUE THREAD

**Issue by nathanleyton** [frugalmechanic/fm-sbt-s3-resolver#51]
This is working absolutely perfectly for resolving regular deps in s3 from build.sbt level however it seems like setURLStreamHandlerFactory is not called in time if you need to register the resolver in the plugins.sbt so that you can actually pull a plugin from s3. The exception you get is:-

[error] java.net.MalformedURLException: unknown protocol: s3

Many Thanks

**Comment by omervk** [comment]
Have you tried placing the `sbt-s3-resolver` plugin inside `project/project/plugins.sbt`, too?

**Comment by omervk** [comment]
Can you share the relevant code from all of your sbt files?

**Comment by jpzk** [comment]
putting it into project/project helped me

**Comment by nathanleyton** [comment]
> putting it into project/project helped me

Are you saying that this helped trying to resolve an sbt plugin that you had deployed to s3 i.e. using addSbtPlugin in plugins.sbt . I was unable to get around this error no matter where i tried to load the plugin from.  I can't really share my sbt files but it is easy to replicate. Build an sbt plugin and publish to s3, then try and load it with addSbtPlugin using s3 resolver . In the mean time we just stick to local publish for our custom sbt plugins everything else works well and we don't change the plugin often. Thanks

**Comment by coreyoconnor** [comment]
One option is to sidestep s3 resolver entirely and load the plugin over http served from s3:

~~~
resolvers += Resolver.url(
  "glngn server releases",
  url("https://glngn-server-releases.s3.amazonaws.com/releases")
)(Resolver.ivyStylePatterns)

addSbtPlugin("glngn" % "sbt-glngn" % "0.3.53")
~~~

This is from: https://gitlab.com/glngn/glngn-server-examples/blob/master/project/plugins.sbt

For the record, adding to `project/project/plugins.sbt` also worked for me. Tho, in my case, the error was from bloop.

**Comment by plavreshin** [comment]
Hi! 

I have encountered a similar issues while trying to resolve custom plugins from S3 by using `fm-sbt-s3-resolver`. 

Using sbt 1.3.9 and  fm-sbt-s3-resolver: 0.19.0

- `project/plugins.sbt`
```
val repoSuffix = "my.custom.repo"
val releaseRepo = s"s3://releases.$repoSuffix"
val snapshotRepo = s"s3://snapshots.$repoSuffix"

resolvers ++= {
  val releases = Resolver.url("Releases resolver", url(releaseRepo))(Resolver.ivyStylePatterns)
  val snapshots = Resolver.url("Snapshots resolver", url(snapshotRepo))(Resolver.ivyStylePatterns)
  Seq(releases, snapshots)
}

addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.19.0")
addSbtPlugin("my.custom.plugin" % "sbt-commons" % "1.2.0-SNAPSHOT")
```

- project/project/plugins.sbt   
```
resolvers += Resolver.jcenterRepo
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.19.0")
```
and it keeps failing with`[error] java.net.MalformedURLException: unknown protocol: s3` no matter what I do. To be more specific here is a detailed log:
```
[debug] Plugins.deducer#function took 1.642442 ms
[info] Loading settings for project my-project-build from plugins.sbt ...
[debug]               Load.resolveProject(my-project-build) took 40.5901ms
[debug]             Load.loadTransitive: finalizeProject(Project(id my-project-build-build, base: /Users/plavreshin/Projects/my-project-build/project, plugins: List(<none>))) took 42.988628ms
[debug] [Loading] Done in /Users/plavreshin/Projects/my-project-build/project, returning: (my-project-build-build)
[debug]           Load.loadUnit: loadedProjectsRaw took 612.713346ms
[debug]           Load.loadUnit: cleanEvalClasses took 1.502126ms
[debug]         Load.loadUnit(file:/Users/plavreshin/Projects/my-project-build/project/, ...) took 3698.485009ms
[debug]       Load.apply: load took 3700.161681ms
[debug]       Load.apply: resolveProjects took 0.157027ms
[debug]       Load.apply: finalTransforms took 16.997157ms
[debug]       Load.apply: config.delegates took 0.313552ms
[error] java.net.MalformedURLException: unknown protocol: s3
[error] 	at java.base/java.net.URL.<init>(URL.java:652)
[error] 	at java.base/java.net.URL.<init>(URL.java:541)
[error] 	at java.base/java.net.URL.<init>(URL.java:488)
[error] 	at sbt.package$.url(package.scala:34)
[error] 	at $8177690ed1833c735631$.$anonfun$$sbtdef$1(/Users/plavreshin/Projects/my-project/project/plugins.sbt:6)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:206)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.net.MalformedURLException: unknown protocol: s3
```

The only way to avoid these issues is to define `fm-sbt-s3-resolver` as a global plugin but this won't help me while building my project on CI.
Once I add it to `~/.sbt/1.0/plugins/plugins.sbt`, everything works like a charm 
 `
[info] Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
`

@tpunder could you please be so kind as to advice - is there anything wrong with fm-sbt-s3-resolver startup order as it seems to work when I define fm-sbt-s3-resolver as a global plugins and fails when it is defined in `project/project/plugins.sbt`?

@jpzk  - could you please share your setup?

**Comment by baldram** [comment]
Hi All! I have a similar scenario - resolving a plugin from S3.
I had some troubles initially, but finally, it worked fine. 

I didn't have to mess with `~./sbt`. All things are set directly within the project files.

 `project/project/build.sbt`
```scala
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.20.0")
```

`project/plugins.sbt`
```scala
sbt.Keys.resolvers += "Lorem Ipsum Snapshots" at "s3://repo.hello.org"

addSbtPlugin("org.hello" % "sbt-lorem-ipsum" % "1.2.3")
```

Works like a charm 👍

**Comment by fernanluyano** [comment]
These solutions don't work for me. It did as mentioned above, and even using a repositories file, I still get "unknown protocol". When I use the https url as suggested, I get forbidden (does not know how to solve the credentials apparently)
