### ISSUE TITLE
Support downloading plugins from s3

### ISSUE THREAD

**Issue by gmalouf** [frugalmechanic/fm-sbt-s3-resolver#8]
The plugin works great for normal dependencies.  This may be limited by sbt, but unfortunately this plugin is not loaded before other plugins get resolved.  

My example is that I have (manually, since publishing from the plugin did not seem to work) uploaded an ivy plugin dependency to my private s3 bucket.  I tried adding the s3 address and the plugin to my plugins.sbt but get: 

java.net.MalformedURLException: unknown protocol: s3

The fm-sbt-s3-resolver plugin is definitely present, but if I do not see a clear way to 'pre-load' the plugin.

**Comment by tpunder** [comment]
I'm not sure if it's possible or not.  Seems like it would be a useful feature though.

If there is a way to trigger initialization of the ```fm.sbt. S3ResolverPlugin``` object then that would get the ```s3://``` url handler registered.

I wonder if a Global Plugin would work:  http://www.scala-sbt.org/0.13/docs/Plugins.html#Global+plugins

Or if you can have a nested ```project/plugins.sbt``` file under your existing project directory.  e.g.: ```project/project/plugins.sbt```

**Comment by mdedetrich** [comment]
I had the same problem, and I can confirm that making a 
`project/project/plugins.sbt`

Solved the problem (it also makes sense if you understand how SBT internals work)

**Comment by tpunder** [comment]
Thanks for verifying!

**Comment by nandotorterolo** [comment]
I have the same problem and suggestion 'project/project/plugins.sbt' works in my local.
but something is wrong when sbt load plugins in travis ci.

```
java.net.MalformedURLException: unknown protocol: s3
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at sbt.package$.url(package.scala:25)
	at $1fc49d0b55810bc8401b$$anonfun$$sbtdef$1$$anonfun$applyOrElse$1.apply(/home/travis/build/WW-Digital/core-milestone-service/project/plugins.sbt:6)
	at $1fc49d0b55810bc8401b$$anonfun$$sbtdef$1$$anonfun$applyOrElse$1.apply(/home/travis/build/WW-Digital/core-milestone-service/project/plugins.sbt:5)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] java.net.MalformedURLException: unknown protocol: s3
[error] Use 'last' for the full log.
```
